CREATE TABLE Seznam (
    cislo_seznamu INT PRIMARY KEY,
    datum DATE NOT NULL,
    kvantita_typu_tiskovin INT NOT NULL CHECK (kvantita_typu_tiskovin >= 0),

    cislo_uctu INT NOT NULL,
    ico_dorucovatele VARCHAR(8) NOT NULL,
    FOREIGN KEY (cislo_uctu, ico_dorucovatele) REFERENCES Dorucovatel(cislo_uctu, ico)
);

CREATE TABLE Seznam_Tiskovina (
    cislo_seznamu INT NOT NULL,
    kod_tiskoviny VARCHAR(20) NOT NULL,
    kvantita INT NOT NULL CHECK (kvantita >= 0),

    PRIMARY KEY (cislo_seznamu, kod_tiskoviny),

    FOREIGN KEY (cislo_seznamu) REFERENCES Seznam(cislo_seznamu) ON DELETE CASCADE,
    FOREIGN KEY (kod_tiskoviny) REFERENCES Tiskovina(kod_tiskoviny) ON DELETE CASCADE
);


--Entita Uzivatel slouží jako nadtyp (supertype) pro následující specializace (subtypy): Spravce, Zakaznik, Dorucovatel. 
-- Zvolený způsob převodu do relačního modelu je "Class Table Inheritance" (jeden nadtyp + tabulky pro každou specializaci). 
-- Každá podtypová tabulka má vlastní atributy a zároveň obsahuje sloupec 'cislo_uctu', který slouží jako cizí klíč odkazující na primární klíč tabulky Uzivatel. 
-- Každá specializace (Spravce, Zakaznik, Dorucovatel) má svůj vlastní -- primární klíč složený z atributu 'cislo_uctu' a jednoznačného identifikátoru: 
-- - Spravce: (cislo_uctu, id) 
-- - Zakaznik: (cislo_uctu, id) 
-- - Dorucovatel: (cislo_uctu, ico) -- 
-- Atribut 'cislo_uctu' je zároveň primárním klíčem v tabulce Uzivatel (nadtyp). 
-- Tento návrh zajišťuje jednoznačné propojení každé specializace na existujícího uživatele, a zároveň umožňuje snadné rozšíření systému o další typy uživatelů.

CREATE SEQUENCE uzivatel_seq START WITH 100001 INCREMENT BY 1;

CREATE TABLE Uzivatel (
    cislo_uctu INT PRIMARY KEY DEFAULT nextval('uzivatel_seq'),
    datum_zalozeni DATE NOT NULL,
    admin_prava BOOLEAN NOT NULL
);


CREATE SEQUENCE spravce_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE Spravce (
    cislo_uctu INT NOT NULL,
    id INT NOT NULL DEFAULT nextval('spravce_id_seq'),
    jmeno_prijmeni TEXT NOT NULL,
    PRIMARY KEY (cislo_uctu, id),
    FOREIGN KEY (cislo_uctu) REFERENCES Uzivatel(cislo_uctu)
);

CREATE SEQUENCE zakaznik_id_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE Zakaznik (
    cislo_uctu INT NOT NULL,
    id INT NOT NULL DEFAULT nextval('zakaznik_id_seq'),
    jmeno_prijmeni TEXT NOT NULL,
    adresa TEXT NOT NULL,
    PRIMARY KEY (cislo_uctu, id),
    FOREIGN KEY (cislo_uctu) REFERENCES Uzivatel(cislo_uctu)
);


CREATE TABLE Dorucovatel (
    cislo_uctu INT NOT NULL,
    ico VARCHAR(8) NOT NULL,
    nazev_spolecnosti TEXT NOT NULL,
    CHECK (LENGTH(ico) = 8 AND ico NOT LIKE '%[^0-9]%'),
    PRIMARY KEY (cislo_uctu, ico),
    FOREIGN KEY (cislo_uctu) REFERENCES Uzivatel(cislo_uctu)
);


CREATE TABLE Tiskovina (
    kod_tiskoviny NUMBER PRIMARY KEY,
    nazev VARCHAR2(100) NOT NULL,
    rok NUMBER NOT NULL,
    nakladatelstvi VARCHAR2(100) NOT NULL,
    rocnik NUMBER,
    cislo NUMBER,
    periodicita VARCHAR2(50),
    typ_tiskoviny VARCHAR2(50),
    dorucovatel_cislo_uctu INT NOT NULL,
    dorucovatel_ico VARCHAR(8) NOT NULL,
    FOREIGN KEY (dorucovatel_cislo_uctu, dorucovatel_ico) REFERENCES Dorucovatel(cislo_uctu, ico)
);




CREATE TABLE Doba_Neodoberania (
    client_ID NUMBER NOT NULL,
    poradi NUMBER NOT NULL,
    zacatek DATE NOT NULL,
    konec DATE,
    PRIMARY KEY (Client_ID, poradi),
    FOREIGN KEY (Client_ID) REFERENCES Zakaznik(cislo_uctu, id)
);

CREATE TABLE Zakaznik_Tiskovina (
    zakaznik_ID NUMBER NOT NULL,
    kod_tiskoviny NUMBER NOT NULL,
    doba_ID NUMBER,
    doba_poradie NUMBER,
    platba NUMBER,
    zakaznik_cislo_uctu INT NOT NULL,
    PRIMARY KEY (zakaznik_cislo_uctu, zakaznik_ID, kod_tiskoviny),
    FOREIGN KEY (zakaznik_cislo_uctu, zakaznik_ID) REFERENCES Zakaznik(cislo_uctu, id),
    FOREIGN KEY (kod_tiskoviny) REFERENCES Tiskovina(kod_tiskoviny),
    FOREIGN KEY (platba) REFERENCES Platba(ID),
    FOREIGN KEY (doba_ID, doba_poradie) REFERENCES Doba_Neodoberania(client_ID, poradi)
);

CREATE TABLE Platba (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variabilnysymbol VARCHAR(50) NOT NULL,
    datum DATE NOT NULL,
    suma DECIMAL(10,2) NOT NULL,
    cislo_odesilatele INT NOT NULL,
    cislo_prijimatele INT NOT NULL,
    FOREIGN KEY (cislo_odesilatele) REFERENCES Uzivatel(cislo_uctu),
    FOREIGN KEY (cislo_prijimatele) REFERENCES Uzivatel(cislo_uctu)
);