BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE uzivatel_seq';
  EXECUTE IMMEDIATE 'DROP SEQUENCE spravce_id_seq';
  EXECUTE IMMEDIATE 'DROP SEQUENCE zakaznik_id_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  FOR obj IN (
    SELECT object_name, object_type
    FROM user_objects
    WHERE object_type IN ('TABLE', 'SEQUENCE')
    AND object_name IN (
      'UZIVATEL', 'SPRAVCE', 'ZAKAZNIK', 'DORUCOVATEL',
      'PLATBA', 'TISKOVINA', 'SEZNAM', 'SEZNAM_TISKOVINA',
      'DOBA_NEODOBERANIA', 'ZAKAZNIK_TISKOVINA',
      'AUDIT_DELETE', 'UZIVATELE_MAPPING',
      'UZIVATEL_SEQ', 'SPRAVCE_ID_SEQ', 'ZAKAZNIK_ID_SEQ'
    )
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP ' || obj.object_type || ' "' || obj.object_name || '" CASCADE CONSTRAINTS';
    EXCEPTION
      WHEN OTHERS THEN NULL;
    END;
  END LOOP;
END;
/


-- Sekvence
CREATE SEQUENCE uzivatel_seq START WITH 100001 INCREMENT BY 1;
CREATE SEQUENCE spravce_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE zakaznik_id_seq START WITH 1 INCREMENT BY 1;

--Entita Uzivatel slouží jako nadtyp (supertype) pro následující specializace (subtypy): Spravce, Zakaznik, Dorucovatel. 
-- Zvolený způsob převodu do relačního modelu je "Class Table Inheritance" (jeden nadtyp + tabulky pro každou specializaci). 
-- Každá podtypová tabulka má vlastní atributy a zároveň obsahuje sloupec 'cislo_uctu', který slouží jako cizí klíč odkazující na primární klíč tabulky Uzivatel. 
-- Každá specializace (Spravce, Zakaznik, Dorucovatel) má svůj vlastní -- primární klíč složený z atributu 'cislo_uctu' a jednoznačného identifikátoru: 
-- - Spravce: (cislo_uctu, id) 
-- - Zakaznik: (cislo_uctu, id) 
-- - Dorucovatel: (cislo_uctu, ico) -- 
-- Atribut 'cislo_uctu' je zároveň primárním klíčem v tabulce Uzivatel (nadtyp). 
-- Tento návrh zajišťuje jednoznačné propojení každé specializace na existujícího uživatele, a zároveň umožňuje snadné rozšíření systému o další typy uživatelů.

-- 1. Nadtyp
CREATE TABLE Uzivatel (
    cislo_uctu INT PRIMARY KEY,
    datum_zalozeni DATE NOT NULL,
    admin_prava NUMBER(1) NOT NULL CHECK (admin_prava IN (0,1))
);

-- 2. Specializace
CREATE TABLE Spravce (
    cislo_uctu INT NOT NULL,
    id INT NOT NULL,
    jmeno_prijmeni VARCHAR2(255) NOT NULL,
    PRIMARY KEY (cislo_uctu, id),
    FOREIGN KEY (cislo_uctu) REFERENCES Uzivatel(cislo_uctu)
);

CREATE TABLE Zakaznik (
    cislo_uctu INT NOT NULL,
    id INT NOT NULL,
    jmeno_prijmeni VARCHAR2(255) NOT NULL,
    adresa VARCHAR2(255) NOT NULL,
    PRIMARY KEY (cislo_uctu, id),
    FOREIGN KEY (cislo_uctu) REFERENCES Uzivatel(cislo_uctu)
);

CREATE TABLE Dorucovatel (
    cislo_uctu INT NOT NULL,
    ico VARCHAR(8) NOT NULL,
    nazev_spolecnosti VARCHAR2(255) NOT NULL,
    CHECK (LENGTH(ico) = 8 AND ico NOT LIKE '%[^0-9]%'),
    PRIMARY KEY (cislo_uctu, ico),
    FOREIGN KEY (cislo_uctu) REFERENCES Uzivatel(cislo_uctu)
);

-- 3. Platba
CREATE TABLE Platba (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variabilnysymbol VARCHAR(50) NOT NULL,
    datum DATE NOT NULL,
    suma DECIMAL(10,2) NOT NULL,
    cislo_odesilatele INT NOT NULL,
    cislo_prijimatele INT NOT NULL,
    FOREIGN KEY (cislo_odesilatele) REFERENCES Uzivatel(cislo_uctu),
    FOREIGN KEY (cislo_prijimatele) REFERENCES Uzivatel(cislo_uctu)
);

-- 4. Tiskovina
CREATE TABLE Tiskovina (
    kod_tiskoviny NUMBER PRIMARY KEY,
    nazev VARCHAR2(100) NOT NULL,
    rok NUMBER NOT NULL,
    nakladatelstvi VARCHAR2(100) NOT NULL,
    rocnik NUMBER,
    cislo NUMBER,
    periodicita VARCHAR2(50),
    typ_tiskoviny VARCHAR2(50),
    dorucovatel_cislo_uctu INT NOT NULL,
    dorucovatel_ico VARCHAR(8) NOT NULL,
    FOREIGN KEY (dorucovatel_cislo_uctu, dorucovatel_ico) REFERENCES Dorucovatel(cislo_uctu, ico)
);

-- 5. Seznam
CREATE TABLE Seznam (
    cislo_seznamu INT PRIMARY KEY,
    datum DATE NOT NULL,
    kvantita_typu_tiskovin INT NOT NULL CHECK (kvantita_typu_tiskovin >= 0),
    cislo_uctu INT NOT NULL,
    ico_dorucovatele VARCHAR(8) NOT NULL,
    FOREIGN KEY (cislo_uctu, ico_dorucovatele) REFERENCES Dorucovatel(cislo_uctu, ico)
);

-- 6. Seznam_Tiskovina
CREATE TABLE Seznam_Tiskovina (
    cislo_seznamu INT NOT NULL,
    kod_tiskoviny NUMBER NOT NULL,
    kvantita INT NOT NULL CHECK (kvantita >= 0),
    PRIMARY KEY (cislo_seznamu, kod_tiskoviny),
    FOREIGN KEY (cislo_seznamu) REFERENCES Seznam(cislo_seznamu) ON DELETE CASCADE,
    FOREIGN KEY (kod_tiskoviny) REFERENCES Tiskovina(kod_tiskoviny) ON DELETE CASCADE
);

-- 7. Doba neodebírání
CREATE TABLE Doba_Neodoberania (
    cislo_uctu NUMBER NOT NULL,
    zakaznik_id NUMBER NOT NULL,
    poradi NUMBER NOT NULL,
    zacatek DATE NOT NULL,
    konec DATE,
    PRIMARY KEY (cislo_uctu, zakaznik_id, poradi),
    FOREIGN KEY (cislo_uctu, zakaznik_id) REFERENCES Zakaznik(cislo_uctu, id)
);

-- 8. Zakaznik_Tiskovina
CREATE TABLE Zakaznik_Tiskovina (
    zakaznik_ID NUMBER NOT NULL,
    kod_tiskoviny NUMBER NOT NULL,
    doba_ID_zakaznika NUMBER,
    doba_cislo_uctu NUMBER,
    doba_poradie NUMBER,
    platba NUMBER,
    zakaznik_cislo_uctu INT NOT NULL,
    PRIMARY KEY (zakaznik_cislo_uctu, zakaznik_ID, kod_tiskoviny),
    FOREIGN KEY (zakaznik_cislo_uctu, zakaznik_ID) REFERENCES Zakaznik(cislo_uctu, id),
    FOREIGN KEY (kod_tiskoviny) REFERENCES Tiskovina(kod_tiskoviny),
    FOREIGN KEY (platba) REFERENCES Platba(ID),
    FOREIGN KEY (doba_cislo_uctu, doba_ID_zakaznika, doba_poradie) REFERENCES Doba_Neodoberania(cislo_uctu, zakaznik_id, poradi)
);

-- Ukázková data

-- Vložení uživatelů
INSERT INTO Uzivatel (cislo_uctu, datum_zalozeni, admin_prava)
VALUES (uzivatel_seq.NEXTVAL, SYSDATE, 1);

INSERT INTO Uzivatel (cislo_uctu, datum_zalozeni, admin_prava)
VALUES (uzivatel_seq.NEXTVAL, SYSDATE, 0);

INSERT INTO Uzivatel (cislo_uctu, datum_zalozeni, admin_prava)
VALUES (uzivatel_seq.NEXTVAL, SYSDATE, 0);

-- Předpokládáme: 100001 = spravce, 100002 = zakaznik, 100003 = dorucovatel

INSERT INTO Uzivatel (cislo_uctu, datum_zalozeni, admin_prava)
VALUES (uzivatel_seq.NEXTVAL, SYSDATE, 0); -- 100004

INSERT INTO Uzivatel (cislo_uctu, datum_zalozeni, admin_prava)
VALUES (uzivatel_seq.NEXTVAL, SYSDATE, 0); -- 100005

INSERT INTO Uzivatel (cislo_uctu, datum_zalozeni, admin_prava)
VALUES (uzivatel_seq.NEXTVAL, SYSDATE, 0); -- 100006

INSERT INTO Uzivatel (cislo_uctu, datum_zalozeni, admin_prava)
VALUES (uzivatel_seq.NEXTVAL, SYSDATE, 0); -- 100007

INSERT INTO Uzivatel (cislo_uctu, datum_zalozeni, admin_prava)
VALUES (uzivatel_seq.NEXTVAL, SYSDATE, 0); -- 100008

INSERT INTO Uzivatel (cislo_uctu, datum_zalozeni, admin_prava)
VALUES (uzivatel_seq.NEXTVAL, SYSDATE, 0); -- 100009

-- Vložení specializací
INSERT INTO Spravce (cislo_uctu, id, jmeno_prijmeni)
VALUES (100001, spravce_id_seq.NEXTVAL, 'Karel Spravce');



INSERT INTO Zakaznik (cislo_uctu, id, jmeno_prijmeni, adresa)
VALUES (100002, zakaznik_id_seq.NEXTVAL, 'Petr Zakaznik', 'Ulice 123, Město');

INSERT INTO Zakaznik (cislo_uctu, id, jmeno_prijmeni, adresa)
VALUES (100004, zakaznik_id_seq.NEXTVAL, 'Alena Nováková', 'Ulice 123, Město'); -- stejná adresa jako Petr Zakaznik

INSERT INTO Zakaznik (cislo_uctu, id, jmeno_prijmeni, adresa)
VALUES (100005, zakaznik_id_seq.NEXTVAL, 'Jan Kovář', 'Hlavní 45, Brno');

INSERT INTO Zakaznik (cislo_uctu, id, jmeno_prijmeni, adresa)
VALUES (100006, zakaznik_id_seq.NEXTVAL, 'Eva Malá', 'Hlavní 45, Brno'); -- stejná adresa jako Jan Kovář

INSERT INTO Zakaznik (cislo_uctu, id, jmeno_prijmeni, adresa)
VALUES (100007, zakaznik_id_seq.NEXTVAL, 'Lukáš Dvořák', 'Nádražní 78, Praha');

INSERT INTO Dorucovatel (cislo_uctu, ico, nazev_spolecnosti)
VALUES (100003, '12345678', 'TiskPost s.r.o.');

INSERT INTO Dorucovatel (cislo_uctu, ico, nazev_spolecnosti)
VALUES (100008, '11112222', 'DoručXpress');

INSERT INTO Dorucovatel (cislo_uctu, ico, nazev_spolecnosti)
VALUES (100009, '33334444', 'MegaPrint CZ');



-- Vložení platby
-- Platba od Petr Zakaznik (100002)
INSERT INTO Platba (variabilnysymbol, datum, suma, cislo_odesilatele, cislo_prijimatele)
VALUES ('20250001', SYSDATE, 199.99, 100002, 100003);

-- Platba od Alena Nováková (100004)
INSERT INTO Platba (variabilnysymbol, datum, suma, cislo_odesilatele, cislo_prijimatele)
VALUES ('20250002', SYSDATE, 149.00, 100004, 100008); -- doručovatel 100008

-- Platba od Jan Kovář (100005)
INSERT INTO Platba (variabilnysymbol, datum, suma, cislo_odesilatele, cislo_prijimatele)
VALUES ('20250003', SYSDATE, 199.00, 100005, 100009);

-- Platba od Eva Malá (100006)
INSERT INTO Platba (variabilnysymbol, datum, suma, cislo_odesilatele, cislo_prijimatele)
VALUES ('20250004', SYSDATE, 179.50, 100006, 100008);

-- Platba od Lukáš Dvořák (100007)
INSERT INTO Platba (variabilnysymbol, datum, suma, cislo_odesilatele, cislo_prijimatele)
VALUES ('20250005', SYSDATE, 210.00, 100007, 100009);


-- Vložení tiskoviny
INSERT INTO Tiskovina (
    kod_tiskoviny, nazev, rok, nakladatelstvi,
    rocnik, cislo, periodicita, typ_tiskoviny,
    dorucovatel_cislo_uctu, dorucovatel_ico
) VALUES (
    1, 'Časopis X', 2025, 'XYZ Media',
    5, 12, 'měsíčník', 'časopis',
    100003, '12345678'
);

INSERT INTO Tiskovina (
    kod_tiskoviny, nazev, rok, nakladatelstvi,
    rocnik, cislo, periodicita, typ_tiskoviny,
    dorucovatel_cislo_uctu, dorucovatel_ico
) VALUES (
    2, 'Magazín Móda', 2025, 'Fashion Media',
    10, 2, 'měsíčník', 'časopis',
    100008, '11112222'
);

INSERT INTO Tiskovina (
    kod_tiskoviny, nazev, rok, nakladatelstvi,
    rocnik, cislo, periodicita, typ_tiskoviny,
    dorucovatel_cislo_uctu, dorucovatel_ico
) VALUES (
    3, 'Technika Dnes', 2025, 'TechPress',
    22, 7, 'čtvrtletník', 'magazín',
    100009, '33334444'
);

-- Vložení doby neodebírání
INSERT INTO Doba_Neodoberania (
    cislo_uctu, zakaznik_id, poradi, zacatek, konec
) VALUES (
    100002, 1, 1,
    TO_DATE('2025-05-01', 'YYYY-MM-DD'),
    TO_DATE('2025-06-30', 'YYYY-MM-DD')
);

INSERT INTO Doba_Neodoberania (
    cislo_uctu, zakaznik_id, poradi, zacatek, konec
) VALUES (
    100005, 3, 1,
    TO_DATE('2025-04-01', 'YYYY-MM-DD'),
    TO_DATE('2025-05-15', 'YYYY-MM-DD')
);




-- Vložení vztahu zakaznik–tiskovina
INSERT INTO Zakaznik_Tiskovina (
    zakaznik_ID, kod_tiskoviny,
    doba_ID_zakaznika, doba_cislo_uctu, doba_poradie,
    platba, zakaznik_cislo_uctu
) VALUES (
    1, 1,
    1, 100002, 1,
    1, 100002
);

-- Zákazník 100004 – tiskovina 2
INSERT INTO Zakaznik_Tiskovina (
    zakaznik_ID, kod_tiskoviny,
    doba_ID_zakaznika, doba_cislo_uctu, doba_poradie,
    platba, zakaznik_cislo_uctu
) VALUES (
    2, 2,
    NULL, NULL, NULL,
    2, 100004
);

-- Zákazník 100005 – tiskovina 3
INSERT INTO Zakaznik_Tiskovina (
    zakaznik_ID, kod_tiskoviny,
    doba_ID_zakaznika, doba_cislo_uctu, doba_poradie,
    platba, zakaznik_cislo_uctu
) VALUES (
    3, 3,
    NULL, NULL, NULL,
    3, 100005
);

-- Zákazník 100006 – tiskovina 2
INSERT INTO Zakaznik_Tiskovina (
    zakaznik_ID, kod_tiskoviny,
    doba_ID_zakaznika, doba_cislo_uctu, doba_poradie,
    platba, zakaznik_cislo_uctu
) VALUES (
    4, 2,
    NULL, NULL, NULL,
    4, 100006
);

-- Zákazník 100007 – tiskovina 3
INSERT INTO Zakaznik_Tiskovina (
    zakaznik_ID, kod_tiskoviny,
    doba_ID_zakaznika, doba_cislo_uctu, doba_poradie,
    platba, zakaznik_cislo_uctu
) VALUES (
    5, 3,
    NULL, NULL, NULL,
    5, 100007
);

INSERT INTO Zakaznik_Tiskovina (
    zakaznik_ID, kod_tiskoviny,
    doba_ID_zakaznika, doba_cislo_uctu, doba_poradie,
    platba, zakaznik_cislo_uctu
) VALUES (
    4,             
    1,              -- kod_tiskoviny (Časopis X, doručuje IČO 12345678)
    NULL, NULL, NULL,
    4,              
    100006          
);


-- Vložení seznamu
-- Seznam 1: doručovatel TiskPost s.r.o. (100003, '12345678')
INSERT INTO Seznam (
    cislo_seznamu, datum, kvantita_typu_tiskovin, cislo_uctu, ico_dorucovatele
) VALUES (
    1, SYSDATE, 1, 100003, '12345678'
);

-- Seznam 2: doručovatel DoručXpress (100008, '11112222')
INSERT INTO Seznam (
    cislo_seznamu, datum, kvantita_typu_tiskovin, cislo_uctu, ico_dorucovatele
) VALUES (
    2, SYSDATE, 1, 100008, '11112222'
);

-- Seznam 3: doručovatel MegaPrint CZ (100009, '33334444')
INSERT INTO Seznam (
    cislo_seznamu, datum, kvantita_typu_tiskovin, cislo_uctu, ico_dorucovatele
) VALUES (
    3, SYSDATE, 1, 100009, '33334444'
);

-- Vložení tiskoviny do seznamu
-- Seznam 1 obsahuje Časopis X (kod_tiskoviny = 1)
INSERT INTO Seznam_Tiskovina (
    cislo_seznamu, kod_tiskoviny, kvantita
) VALUES (
    1, 1, 100
);

-- Seznam 2 obsahuje Magazín Móda (kod_tiskoviny = 2)
INSERT INTO Seznam_Tiskovina (
    cislo_seznamu, kod_tiskoviny, kvantita
) VALUES (
    2, 2, 250
);

-- Seznam 3 obsahuje Technika Dnes (kod_tiskoviny = 3)
INSERT INTO Seznam_Tiskovina (
    cislo_seznamu, kod_tiskoviny, kvantita
) VALUES (
    3, 3, 300
);
-- Index na zakaznik_tiskovina & EXPLAIN PLAN před/po indexu

--  Explain plan pred indexom
    EXPLAIN PLAN FOR
    SELECT *
    FROM Zakaznik z
    JOIN Zakaznik_Tiskovina zt 
    ON z.cislo_uctu = zt.zakaznik_cislo_uctu AND z.id = zt.zakaznik_ID
    JOIN Tiskovina t 
    ON t.kod_tiskoviny = zt.kod_tiskoviny;

-- Zobrazenie plánu pred indexáciu
    SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- Indexácia
    CREATE INDEX idx_zt_kt ON Zakaznik_Tiskovina(kod_tiskoviny);

-- Explain plan po indexe
    EXPLAIN PLAN FOR
    SELECT *
    FROM Zakaznik z
    JOIN Zakaznik_Tiskovina zt 
    ON z.cislo_uctu = zt.zakaznik_cislo_uctu AND z.id = zt.zakaznik_ID
    JOIN Tiskovina t 
    ON t.kod_tiskoviny = zt.kod_tiskoviny;
-- Zobrazenie po indexácii
    SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- Další EXPLAIN PLAN + GROUP BY
    -- Dotaz – počet predplatiteľov na každú tiskovinu
    EXPLAIN PLAN FOR
    SELECT 
        t.nazev,
        COUNT(DISTINCT zt.zakaznik_ID) AS pocet_predplatitelu
    FROM 
        Tiskovina t
    JOIN 
        Zakaznik_Tiskovina zt ON t.kod_tiskoviny = zt.kod_tiskoviny
    GROUP BY 
        t.nazev;

    -- zobrazenie pred optimalizáciou
    SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

    -- Optimalizácia pomocou kombinovaného indexu -> zrychluje join a count(DISTINCT)
    CREATE INDEX idx_zt_kt_id ON Zakaznik_Tiskovina(kod_tiskoviny, zakaznik_ID);

    EXPLAIN PLAN FOR
    SELECT 
        t.nazev,
        COUNT(DISTINCT zt.zakaznik_ID) AS pocet_predplatitelu
    FROM 
        Tiskovina t
    JOIN 
        Zakaznik_Tiskovina zt ON t.kod_tiskoviny = zt.kod_tiskoviny
    GROUP BY 
        t.nazev;

    -- Zobrazenie po optimalizácii
    SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- Vytvorenie 2. uzivatela v databaze
    CREATE USER kolega IDENTIFIED BY kolega123;
    -- zakladne prava
    GRANT CONNECT TO kolega;
    GRANT CREATE SESSION TO kolega;
    -- pristupove prava
    GRANT SELECT, INSERT ON Zakaznik TO kolega;
    GRANT SELECT, INSERT ON Tiskovina TO kolega;
    GRANT SELECT, INSERT ON Zakaznik_Tiskovina TO kolega;
    GRANT SELECT ON Platba TO kolega;

    -- Materializovaný prehľad nad vopred špecifikovanými datami, kolega nemá práva k vytváraniu nových
    CREATE MATERIALIZED VIEW kolega.v_prehled_platby AS
    SELECT 
        zt.zakaznik_ID,
        zt.kod_tiskoviny,
        t.nazev,
        zt.platba
    FROM 
        Zakaznik_Tiskovina zt
    JOIN 
        Tiskovina t ON zt.kod_tiskoviny = t.kod_tiskoviny;

    -- select checking
    SELECT * FROM kolega.v_prehled_platby;
-- Dotazy

-- Zobrazí všetchny platby uskutečněné zákazníky
SELECT z.jmeno_prijmeni, p.variabilnysymbol, p.suma, p.datum
FROM Zakaznik z
JOIN Platba p ON z.cislo_uctu = p.cislo_odesilatele;

-- Zjistí, který doručovatel distribuuje jaké tiskoviny
SELECT t.nazev, d.nazev_spolecnosti
FROM Tiskovina t
JOIN Dorucovatel d 
  ON t.dorucovatel_cislo_uctu = d.cislo_uctu 
 AND t.dorucovatel_ico = d.ico;


-- Zjistí, který zákazník zaplatil kterou tiskovinu
SELECT z.jmeno_prijmeni, t.nazev, p.suma, p.datum
FROM Zakaznik z
JOIN Zakaznik_Tiskovina zt 
  ON z.cislo_uctu = zt.zakaznik_cislo_uctu 
 AND z.id = zt.zakaznik_ID
JOIN Tiskovina t 
  ON t.kod_tiskoviny = zt.kod_tiskoviny
JOIN Platba p 
  ON p.ID = zt.platba;

--koľik zákazníků bydlí na jednotlivých adresách
SELECT adresa, COUNT(*) AS pocet_zakazniku
FROM Zakaznik
GROUP BY adresa;

--jaký je celkový prijem každého doručovatele
SELECT d.nazev_spolecnosti, p.cislo_prijimatele, SUM(p.suma) AS celkova_suma
FROM Platba p
JOIN Dorucovatel d ON p.cislo_prijimatele = d.cislo_uctu
GROUP BY d.nazev_spolecnosti, p.cislo_prijimatele;

-- Zobrazí zákazníky, kteří si dočasně prerušili odber
SELECT z.jmeno_prijmeni
FROM Zakaznik z
WHERE EXISTS (
    SELECT 1
    FROM Doba_Neodoberania d
    WHERE d.cislo_uctu = z.cislo_uctu
      AND d.zakaznik_id = z.id
      AND d.konec IS NOT NULL
);

-- Zobrazí jmená zákazníkov, ktorí majú predplatné na tlačoviny doručované firmou s IČO 12345678.
SELECT z.jmeno_prijmeni
FROM Zakaznik z
WHERE z.cislo_uctu IN (
    SELECT zt.zakaznik_cislo_uctu
    FROM Zakaznik_Tiskovina zt
    JOIN Tiskovina t 
      ON zt.kod_tiskoviny = t.kod_tiskoviny
    WHERE t.dorucovatel_ico = '12345678'
);


CREATE TABLE Audit_Delete (
  audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kdy TIMESTAMP DEFAULT SYSTIMESTAMP,
  uzivatel NUMBER,  
  pocet_zbyvajicich NUMBER,
  komentar VARCHAR2(255),
  FOREIGN KEY (uzivatel) REFERENCES Uzivatel(cislo_uctu)
);

CREATE TABLE Uzivatele_Mapping (
  db_user VARCHAR2(30) PRIMARY KEY,       -- Oracle USER 
  cislo_uctu INT NOT NULL,                -- odpovídající uživatelský účet
  FOREIGN KEY (cislo_uctu) REFERENCES Uzivatel(cislo_uctu)
);

-- Administrátor (Karel Spravce) – Oracle uživatel XLISKAH00
INSERT INTO Uzivatele_Mapping (db_user, cislo_uctu)
VALUES ('XLISKAH00', 100001);

-- Zákazník (Petr Zakaznik) – Oracle uživatel ZAKPET01
INSERT INTO Uzivatele_Mapping (db_user, cislo_uctu)
VALUES ('ZAKPET01', 100002);

-- Doručovatel (TiskPost s.r.o.) – Oracle uživatel DORPOST1
INSERT INTO Uzivatele_Mapping (db_user, cislo_uctu)
VALUES ('DORPOST1', 100003);

-- Zákazník (Alena Nováková) – Oracle uživatel ZAKALEN1
INSERT INTO Uzivatele_Mapping (db_user, cislo_uctu)
VALUES ('ZAKALEN1', 100004);

-- Zákazník (Jan Kovář) – Oracle uživatel ZAKJAN01
INSERT INTO Uzivatele_Mapping (db_user, cislo_uctu)
VALUES ('ZAKJAN01', 100005);

-- Zákazník (Eva Malá) – Oracle uživatel ZAKEVA01
INSERT INTO Uzivatele_Mapping (db_user, cislo_uctu)
VALUES ('ZAKEVA01', 100006);

-- Zákazník (Lukáš Dvořák) – Oracle uživatel ZAKLUK01
INSERT INTO Uzivatele_Mapping (db_user, cislo_uctu)
VALUES ('ZAKLUK01', 100007);

-- Doručovatel (DoručXpress) – Oracle uživatel DORDXPRS
INSERT INTO Uzivatele_Mapping (db_user, cislo_uctu)
VALUES ('DORDXPRS', 100008);

-- Doručovatel (MegaPrint CZ) – Oracle uživatel DORMEGA1
INSERT INTO Uzivatele_Mapping (db_user, cislo_uctu)
VALUES ('DORMEGA1', 100009);


-- Trigger `audit_mazani_plateb` slouží k auditu každé operace DELETE
-- na tabulce `Platba`. Reaguje na příkaz DELETE tím, že:
-- 
-- 1. Pomocí Oracle funkce `USER` zjistí, kdo je aktuálně přihlášený
--    databázový uživatel (např. 'XLISKAH00').
--
-- 2. Pomocí mapovací tabulky `Uzivatele_Mapping` zjistí, který z
--    aplikačních uživatelů (tabulka `Uzivatel`) odpovídá tomuto
--    databázovému účtu – tedy získá `cislo_uctu`.
--
-- 3. Z tabulky `Uzivatel` následně získá informaci, zda má uživatel
--    administrátorská práva (`admin_prava`).
--
-- 4. Spočítá, kolik záznamů po provedeném DELETE v tabulce `Platba`
--    zůstává (nejde zjistit kolik jich bylo smazáno, protože Oracle
--    to v příkazovém triggeru neumožňuje přímo).
--
-- 5. Vloží do auditní tabulky `Audit_Delete` informaci o:
--    - čísle účtu uživatele (`cislo_uctu`)
--    - počtu záznamů, které v `Platba` zůstaly
--    - textovém komentáři podle typu oprávnění
--    - čase operace (defaultně přes TIMESTAMP sloupec `kdy`)

CREATE OR REPLACE TRIGGER audit_mazani_plateb
AFTER DELETE ON Platba
DECLARE
  id_uzivatele Uzivatel.cislo_uctu%TYPE;
  je_admin     Uzivatel.admin_prava%TYPE;
  pocet        NUMBER;
  komentar     VARCHAR2(255);
BEGIN
  -- Zjisti přihlášeného uživatele z mapovací tabulky
  BEGIN
    SELECT u.cislo_uctu, u.admin_prava
    INTO id_uzivatele, je_admin
    FROM Uzivatel u
    JOIN Uzivatele_Mapping m ON u.cislo_uctu = m.cislo_uctu
    WHERE UPPER(m.db_user) = UPPER(USER);
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      id_uzivatele := NULL;
      je_admin := NULL;
      komentar := 'Mazání provedeno neznámým nebo nezmapovaným uživatelem.';
  END;

  -- Vytvoř komentář na základě oprávnění
  IF je_admin = 1 THEN
    komentar := 'Mazání provedeno administrátorem.';
  ELSIF je_admin = 0 THEN
    komentar := 'Mazání provedeno běžným uživatelem.';
  END IF;

  -- Spočítej zbylé záznamy v tabulce Platba
  SELECT COUNT(*) INTO pocet FROM Platba;

  -- Zaloguj do auditní tabulky
  INSERT INTO Audit_Delete (uzivatel, pocet_zbyvajicich, komentar)
  VALUES (id_uzivatele, pocet, komentar);
END;
/

DELETE FROM Zakaznik_Tiskovina
WHERE platba = (SELECT id FROM Platba WHERE ROWNUM = 1);

DELETE FROM Platba WHERE ROWNUM = 1;
COMMIT;

SELECT 
  a.audit_id,
  a.kdy,
  a.uzivatel AS cislo_uctu,
  u.admin_prava,
  u.cislo_uctu,
  s.jmeno_prijmeni,
  a.pocet_zbyvajicich,
  a.komentar
FROM Audit_Delete a
LEFT JOIN Uzivatel u ON a.uzivatel = u.cislo_uctu
LEFT JOIN (
    SELECT cislo_uctu, jmeno_prijmeni FROM Spravce
    UNION ALL
    SELECT cislo_uctu, jmeno_prijmeni FROM Zakaznik
) s ON a.uzivatel = s.cislo_uctu
ORDER BY a.audit_id DESC;



-- Trigger UPDATE_ICO_DORUCOVATELE zajišťuje, že pokud dojde ke změně IČO v tabulce DORUCOVATEL,
-- automaticky se tato nová hodnota promítne i do všech závislých tabulek: TISKOVINA a SEZNAM.
-- Konkrétně aktualizuje:
--   - sloupec TISKOVINA.dorucovatel_ico
--   - sloupec SEZNAM.ico_dorucovatele
-- Spouští se po změně sloupce "ico" v tabulce DORUCOVATEL (AFTER UPDATE OF ico).
-- 
-- Aby mohl tento trigger fungovat:
--   - je nutné dočasně odstranit cizí klíče z tabulek TISKOVINA a SEZNAM, které brání změně hodnoty v DORUCOVATEL
--   - po provedení změny lze tyto cizí klíče znovu přidat
-- 
-- Trigger tímto způsobem simuluje chování ON UPDATE CASCADE, které Oracle běžně nepodporuje.


CREATE OR REPLACE TRIGGER update_ico_dorucovatele
AFTER UPDATE OF ico ON Dorucovatel
FOR EACH ROW
BEGIN
  -- Aktualizace IČO v tabulce TISKOVINA
  UPDATE Tiskovina
  SET dorucovatel_ico = :NEW.ico
  WHERE dorucovatel_cislo_uctu = :OLD.cislo_uctu
    AND dorucovatel_ico = :OLD.ico;

  -- Aktualizace IČO v tabulce SEZNAM
  UPDATE Seznam
  SET ico_dorucovatele = :NEW.ico
  WHERE cislo_uctu = :OLD.cislo_uctu
    AND ico_dorucovatele = :OLD.ico;
END;
/


-- Odstranění cizího klíče z Tiskovina a Seznam na Dorucovatel
BEGIN
  FOR c IN (
    SELECT constraint_name, table_name
    FROM user_constraints
    WHERE constraint_type = 'R'
      AND r_owner = USER
      AND r_constraint_name IN (
        SELECT constraint_name
        FROM user_constraints
        WHERE table_name = 'DORUCOVATEL'
          AND constraint_type = 'P'
      )
      AND table_name IN ('SEZNAM', 'TISKOVINA')
  ) LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE ' || c.table_name || ' DROP CONSTRAINT ' || c.constraint_name;
  END LOOP;
END;
/

UPDATE Dorucovatel
SET ico = '87654321'
WHERE ico = '12345678';

COMMIT;

-- Obnovení cizích klíčů
ALTER TABLE Tiskovina ADD CONSTRAINT fk_tiskovina_dorucovatel
  FOREIGN KEY (dorucovatel_cislo_uctu, dorucovatel_ico)
  REFERENCES Dorucovatel(cislo_uctu, ico);

ALTER TABLE Seznam ADD CONSTRAINT fk_seznam_dorucovatel
  FOREIGN KEY (cislo_uctu, ico_dorucovatele)
  REFERENCES Dorucovatel(cislo_uctu, ico);






SELECT kod_tiskoviny, dorucovatel_ico
FROM Tiskovina
WHERE dorucovatel_ico = '87654321';

-- Tiskoviny, kde byl změněn doručovatel
SELECT kod_tiskoviny, dorucovatel_cislo_uctu, dorucovatel_ico
FROM Tiskovina
WHERE dorucovatel_ico = '87654321';

-- Seznamy, kde byl změněn doručovatel
SELECT cislo_seznamu, cislo_uctu, ico_dorucovatele
FROM Seznam
WHERE ico_dorucovatele = '87654321';



-- Procedura VLOZ_NOVOU_PLATBU:
-- Přidá novou platbu od zákazníka na základě jeho jména a IČO doručovatele.
-- Pokud zákazník nebo doručovatel neexistují, vyvolá výjimku.
-- Používá datové typy %TYPE, kontrolu existence, a EXCEPTION blok.

CREATE OR REPLACE PROCEDURE vloz_novou_platbu (
  jmeno_zakaznika IN Zakaznik.jmeno_prijmeni%TYPE,
  ico_dorucovatele IN Dorucovatel.ico%TYPE,
  variabilni_symbol IN Platba.variabilnysymbol%TYPE,
  castka IN Platba.suma%TYPE
)
IS
  zakaznik_ucet Uzivatel.cislo_uctu%TYPE;
  dorucovatel_ucet Uzivatel.cislo_uctu%TYPE;
BEGIN
  -- Získání cisla_uctu zákazníka podle jména
  SELECT z.cislo_uctu
  INTO zakaznik_ucet
  FROM Zakaznik z
  WHERE z.jmeno_prijmeni = jmeno_zakaznika;

  -- Získání cisla_uctu doručovatele podle IČO
  SELECT d.cislo_uctu
  INTO dorucovatel_ucet
  FROM Dorucovatel d
  WHERE d.ico = ico_dorucovatele;

  -- Vložení nové platby
  INSERT INTO Platba (variabilnysymbol, datum, suma, cislo_odesilatele, cislo_prijimatele)
  VALUES (variabilni_symbol, SYSDATE, castka, zakaznik_ucet, dorucovatel_ucet);

  DBMS_OUTPUT.PUT_LINE('Platba vložena úspěšně.');

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Zákazník nebo doručovatel nebyl nalezen.');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Chyba při vkládání platby: ' || SQLERRM);
END;
/


BEGIN
  vloz_novou_platbu(
    jmeno_zakaznika => 'Petr Zakaznik',
    ico_dorucovatele => '87654321',
    variabilni_symbol => 'TEST_01',
    castka => 180.00
  );
  vloz_novou_platbu(
    jmeno_zakaznika => 'Petr Zakaznik',
    ico_dorucovatele => '11112222',
    variabilni_symbol => 'TEST_02',
    castka => 199.90
  );
  vloz_novou_platbu(
    jmeno_zakaznika => 'Petr Zakaznik',
    ico_dorucovatele => '87654321',
    variabilni_symbol => 'TEST_03',
    castka => 159.00
  );
END;
/



BEGIN
  vloz_novou_platbu(
    jmeno_zakaznika => 'Neexistujici Uzivatel',  
    ico_dorucovatele => '00000000',              
    variabilni_symbol => 'TEST_FAIL',
    castka => 100.00
  );
END;
/

-- kontrloa vložení platby
SELECT
  p.ID,
  p.variabilnysymbol,
  p.suma,
  p.datum,
  z.jmeno_prijmeni AS zakaznik,
  d.nazev_spolecnosti AS dorucovatel
FROM Platba p
JOIN Zakaznik z ON z.cislo_uctu = p.cislo_odesilatele
JOIN Dorucovatel d ON d.cislo_uctu = p.cislo_prijimatele
WHERE p.variabilnysymbol = 'TEST_O1';  

-- Procedura VYPIS_PLATBY_ZAKAZNIKU:
-- Vypíše všechny platby od zákazníka podle jména.
-- Používá kurzor, %ROWTYPE, výpis pomocí DBMS_OUTPUT a ošetření výjimek.

CREATE OR REPLACE PROCEDURE vypis_platby_zakazniku (
  jmeno_zakaznika IN Zakaznik.jmeno_prijmeni%TYPE
)
IS
  zakaznik_cislo Uzivatel.cislo_uctu%TYPE;

  CURSOR platby_cur IS
    SELECT p.*, d.nazev_spolecnosti
    FROM Platba p
    JOIN Dorucovatel d ON p.cislo_prijimatele = d.cislo_uctu
    WHERE p.cislo_odesilatele = zakaznik_cislo;

  platba_rec platby_cur%ROWTYPE;
BEGIN
  -- Získání cisla_uctu podle jména zákazníka
  SELECT z.cislo_uctu
  INTO zakaznik_cislo
  FROM Zakaznik z
  WHERE z.jmeno_prijmeni = jmeno_zakaznika;

  -- Otevření kurzoru
  OPEN platby_cur;
  LOOP
    FETCH platby_cur INTO platba_rec;
    EXIT WHEN platby_cur%NOTFOUND;

    -- Výpis jedné platby
    DBMS_OUTPUT.PUT_LINE(
      'Datum: ' || TO_CHAR(platba_rec.datum, 'DD.MM.YYYY') ||
      ', Částka: ' || platba_rec.suma ||
      ', VS: ' || platba_rec.variabilnysymbol ||
      ', Příjemce: ' || platba_rec.nazev_spolecnosti ||
      ' (Účet: ' || platba_rec.cislo_prijimatele || ')'
    );
  END LOOP;
  CLOSE platby_cur;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Zákazník nebyl nalezen.');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Chyba při výpisu plateb: ' || SQLERRM);
END;
/

BEGIN
  vypis_platby_zakazniku('Petr Zakaznik');
END;
/


-- Tento dotaz zobrazuje všechny zákazníky spolu s jejich adresou, stavem předplatného a seznamem odebíraných tiskovin.
-- Stav předplatného je určen pomocí CASE:
--  - 'Pozastaveno', pokud má zákazník právě aktivní záznam o dočasném přerušení odběru
--  - 'Aktivní', pokud má přiřazenou alespoň jednu tiskovinu
--  - 'Bez předplatného', pokud žádné předplatné nemá
-- Pomocí LISTAGG jsou názvy tiskovin spojeny do jednoho sloupce.

WITH zakaznici_s_predplatnym AS (
  SELECT DISTINCT zt.zakaznik_cislo_uctu, zt.zakaznik_id
  FROM Zakaznik_Tiskovina zt
),
tiskoviny_uzivatele AS (
  SELECT
    zt.zakaznik_cislo_uctu,
    zt.zakaznik_id,
    LISTAGG(t.nazev, ', ') WITHIN GROUP (ORDER BY t.nazev) AS tiskoviny
  FROM Zakaznik_Tiskovina zt
  JOIN Tiskovina t ON zt.kod_tiskoviny = t.kod_tiskoviny
  GROUP BY zt.zakaznik_cislo_uctu, zt.zakaznik_id
)
SELECT 
  z.jmeno_prijmeni,
  z.adresa,
  CASE
    WHEN EXISTS (
      SELECT 1
      FROM Doba_Neodoberania d
      WHERE d.cislo_uctu = z.cislo_uctu
        AND d.zakaznik_id = z.id
        AND SYSDATE BETWEEN d.zacatek AND NVL(d.konec, SYSDATE)
    ) THEN 'Pozastaveno'
    WHEN zp.zakaznik_cislo_uctu IS NOT NULL THEN 'Aktivní'
    ELSE 'Bez předplatného'
  END AS stav_predplatne,
  NVL(tu.tiskoviny, '–') AS odebira
FROM Zakaznik z
LEFT JOIN zakaznici_s_predplatnym zp
  ON z.cislo_uctu = zp.zakaznik_cislo_uctu AND z.id = zp.zakaznik_id
LEFT JOIN tiskoviny_uzivatele tu
  ON z.cislo_uctu = tu.zakaznik_cislo_uctu AND z.id = tu.zakaznik_id
ORDER BY z.jmeno_prijmeni;