BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE uzivatel_seq';
  EXECUTE IMMEDIATE 'DROP SEQUENCE spravce_id_seq';
  EXECUTE IMMEDIATE 'DROP SEQUENCE zakaznik_id_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  FOR obj IN (
    SELECT object_name, object_type
    FROM user_objects
    WHERE object_type IN ('TABLE', 'SEQUENCE')
    AND object_name IN (
      'UZIVATEL', 'SPRAVCE', 'ZAKAZNIK', 'DORUCOVATEL',
      'PLATBA', 'TISKOVINA', 'SEZNAM', 'SEZNAM_TISKOVINA',
      'DOBA_NEODOBERANIA', 'ZAKAZNIK_TISKOVINA',
      'UZIVATEL_SEQ', 'SPRAVCE_ID_SEQ', 'ZAKAZNIK_ID_SEQ'
    )
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP ' || obj.object_type || ' "' || obj.object_name || '" CASCADE CONSTRAINTS';
    EXCEPTION
      WHEN OTHERS THEN NULL;
    END;
  END LOOP;
END;
/


-- Sekvence
CREATE SEQUENCE uzivatel_seq START WITH 100001 INCREMENT BY 1;
CREATE SEQUENCE spravce_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE zakaznik_id_seq START WITH 1 INCREMENT BY 1;

--Entita Uzivatel slouží jako nadtyp (supertype) pro následující specializace (subtypy): Spravce, Zakaznik, Dorucovatel. 
-- Zvolený způsob převodu do relačního modelu je "Class Table Inheritance" (jeden nadtyp + tabulky pro každou specializaci). 
-- Každá podtypová tabulka má vlastní atributy a zároveň obsahuje sloupec 'cislo_uctu', který slouží jako cizí klíč odkazující na primární klíč tabulky Uzivatel. 
-- Každá specializace (Spravce, Zakaznik, Dorucovatel) má svůj vlastní -- primární klíč složený z atributu 'cislo_uctu' a jednoznačného identifikátoru: 
-- - Spravce: (cislo_uctu, id) 
-- - Zakaznik: (cislo_uctu, id) 
-- - Dorucovatel: (cislo_uctu, ico) -- 
-- Atribut 'cislo_uctu' je zároveň primárním klíčem v tabulce Uzivatel (nadtyp). 
-- Tento návrh zajišťuje jednoznačné propojení každé specializace na existujícího uživatele, a zároveň umožňuje snadné rozšíření systému o další typy uživatelů.

-- 1. Nadtyp
CREATE TABLE Uzivatel (
    cislo_uctu INT PRIMARY KEY,
    datum_zalozeni DATE NOT NULL,
    admin_prava NUMBER(1) NOT NULL CHECK (admin_prava IN (0,1))
);

-- 2. Specializace
CREATE TABLE Spravce (
    cislo_uctu INT NOT NULL,
    id INT NOT NULL,
    jmeno_prijmeni VARCHAR2(255) NOT NULL,
    PRIMARY KEY (cislo_uctu, id),
    FOREIGN KEY (cislo_uctu) REFERENCES Uzivatel(cislo_uctu)
);

CREATE TABLE Zakaznik (
    cislo_uctu INT NOT NULL,
    id INT NOT NULL,
    jmeno_prijmeni VARCHAR2(255) NOT NULL,
    adresa VARCHAR2(255) NOT NULL,
    PRIMARY KEY (cislo_uctu, id),
    FOREIGN KEY (cislo_uctu) REFERENCES Uzivatel(cislo_uctu)
);

CREATE TABLE Dorucovatel (
    cislo_uctu INT NOT NULL,
    ico VARCHAR(8) NOT NULL,
    nazev_spolecnosti VARCHAR2(255) NOT NULL,
    CHECK (LENGTH(ico) = 8 AND ico NOT LIKE '%[^0-9]%'),
    PRIMARY KEY (cislo_uctu, ico),
    FOREIGN KEY (cislo_uctu) REFERENCES Uzivatel(cislo_uctu)
);

-- 3. Platba
CREATE TABLE Platba (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variabilnysymbol VARCHAR(50) NOT NULL,
    datum DATE NOT NULL,
    suma DECIMAL(10,2) NOT NULL,
    cislo_odesilatele INT NOT NULL,
    cislo_prijimatele INT NOT NULL,
    FOREIGN KEY (cislo_odesilatele) REFERENCES Uzivatel(cislo_uctu),
    FOREIGN KEY (cislo_prijimatele) REFERENCES Uzivatel(cislo_uctu)
);

-- 4. Tiskovina
CREATE TABLE Tiskovina (
    kod_tiskoviny NUMBER PRIMARY KEY,
    nazev VARCHAR2(100) NOT NULL,
    rok NUMBER NOT NULL,
    nakladatelstvi VARCHAR2(100) NOT NULL,
    rocnik NUMBER,
    cislo NUMBER,
    periodicita VARCHAR2(50),
    typ_tiskoviny VARCHAR2(50),
    dorucovatel_cislo_uctu INT NOT NULL,
    dorucovatel_ico VARCHAR(8) NOT NULL,
    FOREIGN KEY (dorucovatel_cislo_uctu, dorucovatel_ico) REFERENCES Dorucovatel(cislo_uctu, ico)
);

-- 5. Seznam
CREATE TABLE Seznam (
    cislo_seznamu INT PRIMARY KEY,
    datum DATE NOT NULL,
    kvantita_typu_tiskovin INT NOT NULL CHECK (kvantita_typu_tiskovin >= 0),
    cislo_uctu INT NOT NULL,
    ico_dorucovatele VARCHAR(8) NOT NULL,
    FOREIGN KEY (cislo_uctu, ico_dorucovatele) REFERENCES Dorucovatel(cislo_uctu, ico)
);

-- 6. Seznam_Tiskovina
CREATE TABLE Seznam_Tiskovina (
    cislo_seznamu INT NOT NULL,
    kod_tiskoviny NUMBER NOT NULL,
    kvantita INT NOT NULL CHECK (kvantita >= 0),
    PRIMARY KEY (cislo_seznamu, kod_tiskoviny),
    FOREIGN KEY (cislo_seznamu) REFERENCES Seznam(cislo_seznamu) ON DELETE CASCADE,
    FOREIGN KEY (kod_tiskoviny) REFERENCES Tiskovina(kod_tiskoviny) ON DELETE CASCADE
);

-- 7. Doba neodebírání
CREATE TABLE Doba_Neodoberania (
    cislo_uctu NUMBER NOT NULL,
    zakaznik_id NUMBER NOT NULL,
    poradi NUMBER NOT NULL,
    zacatek DATE NOT NULL,
    konec DATE,
    PRIMARY KEY (cislo_uctu, zakaznik_id, poradi),
    FOREIGN KEY (cislo_uctu, zakaznik_id) REFERENCES Zakaznik(cislo_uctu, id)
);

-- 8. Zakaznik_Tiskovina
CREATE TABLE Zakaznik_Tiskovina (
    zakaznik_ID NUMBER NOT NULL,
    kod_tiskoviny NUMBER NOT NULL,
    doba_ID_zakaznika NUMBER,
    doba_cislo_uctu NUMBER,
    doba_poradie NUMBER,
    platba NUMBER,
    zakaznik_cislo_uctu INT NOT NULL,
    PRIMARY KEY (zakaznik_cislo_uctu, zakaznik_ID, kod_tiskoviny),
    FOREIGN KEY (zakaznik_cislo_uctu, zakaznik_ID) REFERENCES Zakaznik(cislo_uctu, id),
    FOREIGN KEY (kod_tiskoviny) REFERENCES Tiskovina(kod_tiskoviny),
    FOREIGN KEY (platba) REFERENCES Platba(ID),
    FOREIGN KEY (doba_cislo_uctu, doba_ID_zakaznika, doba_poradie) REFERENCES Doba_Neodoberania(cislo_uctu, zakaznik_id, poradi)
);

-- Ukázková data

-- Vložení uživatelů
INSERT INTO Uzivatel (cislo_uctu, datum_zalozeni, admin_prava)
VALUES (uzivatel_seq.NEXTVAL, SYSDATE, 1);

INSERT INTO Uzivatel (cislo_uctu, datum_zalozeni, admin_prava)
VALUES (uzivatel_seq.NEXTVAL, SYSDATE, 0);

INSERT INTO Uzivatel (cislo_uctu, datum_zalozeni, admin_prava)
VALUES (uzivatel_seq.NEXTVAL, SYSDATE, 0);

-- Předpokládáme: 100001 = spravce, 100002 = zakaznik, 100003 = dorucovatel

INSERT INTO Uzivatel (cislo_uctu, datum_zalozeni, admin_prava)
VALUES (uzivatel_seq.NEXTVAL, SYSDATE, 0); -- 100004

INSERT INTO Uzivatel (cislo_uctu, datum_zalozeni, admin_prava)
VALUES (uzivatel_seq.NEXTVAL, SYSDATE, 0); -- 100005

INSERT INTO Uzivatel (cislo_uctu, datum_zalozeni, admin_prava)
VALUES (uzivatel_seq.NEXTVAL, SYSDATE, 0); -- 100006

INSERT INTO Uzivatel (cislo_uctu, datum_zalozeni, admin_prava)
VALUES (uzivatel_seq.NEXTVAL, SYSDATE, 0); -- 100007

INSERT INTO Uzivatel (cislo_uctu, datum_zalozeni, admin_prava)
VALUES (uzivatel_seq.NEXTVAL, SYSDATE, 0); -- 100008

INSERT INTO Uzivatel (cislo_uctu, datum_zalozeni, admin_prava)
VALUES (uzivatel_seq.NEXTVAL, SYSDATE, 0); -- 100009

-- Vložení specializací
INSERT INTO Spravce (cislo_uctu, id, jmeno_prijmeni)
VALUES (100001, spravce_id_seq.NEXTVAL, 'Karel Spravce');



INSERT INTO Zakaznik (cislo_uctu, id, jmeno_prijmeni, adresa)
VALUES (100002, zakaznik_id_seq.NEXTVAL, 'Petr Zakaznik', 'Ulice 123, Město');

INSERT INTO Zakaznik (cislo_uctu, id, jmeno_prijmeni, adresa)
VALUES (100004, zakaznik_id_seq.NEXTVAL, 'Alena Nováková', 'Ulice 123, Město'); -- stejná adresa jako Petr Zakaznik

INSERT INTO Zakaznik (cislo_uctu, id, jmeno_prijmeni, adresa)
VALUES (100005, zakaznik_id_seq.NEXTVAL, 'Jan Kovář', 'Hlavní 45, Brno');

INSERT INTO Zakaznik (cislo_uctu, id, jmeno_prijmeni, adresa)
VALUES (100006, zakaznik_id_seq.NEXTVAL, 'Eva Malá', 'Hlavní 45, Brno'); -- stejná adresa jako Jan Kovář

INSERT INTO Zakaznik (cislo_uctu, id, jmeno_prijmeni, adresa)
VALUES (100007, zakaznik_id_seq.NEXTVAL, 'Lukáš Dvořák', 'Nádražní 78, Praha');

INSERT INTO Dorucovatel (cislo_uctu, ico, nazev_spolecnosti)
VALUES (100003, '12345678', 'TiskPost s.r.o.');

INSERT INTO Dorucovatel (cislo_uctu, ico, nazev_spolecnosti)
VALUES (100008, '11112222', 'DoručXpress');

INSERT INTO Dorucovatel (cislo_uctu, ico, nazev_spolecnosti)
VALUES (100009, '33334444', 'MegaPrint CZ');



-- Vložení platby
-- Platba od Petr Zakaznik (100002)
INSERT INTO Platba (variabilnysymbol, datum, suma, cislo_odesilatele, cislo_prijimatele)
VALUES ('20250001', SYSDATE, 199.99, 100002, 100003);

-- Platba od Alena Nováková (100004)
INSERT INTO Platba (variabilnysymbol, datum, suma, cislo_odesilatele, cislo_prijimatele)
VALUES ('20250002', SYSDATE, 149.00, 100004, 100008); -- doručovatel 100008

-- Platba od Jan Kovář (100005)
INSERT INTO Platba (variabilnysymbol, datum, suma, cislo_odesilatele, cislo_prijimatele)
VALUES ('20250003', SYSDATE, 199.00, 100005, 100009);

-- Platba od Eva Malá (100006)
INSERT INTO Platba (variabilnysymbol, datum, suma, cislo_odesilatele, cislo_prijimatele)
VALUES ('20250004', SYSDATE, 179.50, 100006, 100008);

-- Platba od Lukáš Dvořák (100007)
INSERT INTO Platba (variabilnysymbol, datum, suma, cislo_odesilatele, cislo_prijimatele)
VALUES ('20250005', SYSDATE, 210.00, 100007, 100009);


-- Vložení tiskoviny
INSERT INTO Tiskovina (
    kod_tiskoviny, nazev, rok, nakladatelstvi,
    rocnik, cislo, periodicita, typ_tiskoviny,
    dorucovatel_cislo_uctu, dorucovatel_ico
) VALUES (
    1, 'Časopis X', 2025, 'XYZ Media',
    5, 12, 'měsíčník', 'časopis',
    100003, '12345678'
);

INSERT INTO Tiskovina (
    kod_tiskoviny, nazev, rok, nakladatelstvi,
    rocnik, cislo, periodicita, typ_tiskoviny,
    dorucovatel_cislo_uctu, dorucovatel_ico
) VALUES (
    2, 'Magazín Móda', 2025, 'Fashion Media',
    10, 2, 'měsíčník', 'časopis',
    100008, '11112222'
);

INSERT INTO Tiskovina (
    kod_tiskoviny, nazev, rok, nakladatelstvi,
    rocnik, cislo, periodicita, typ_tiskoviny,
    dorucovatel_cislo_uctu, dorucovatel_ico
) VALUES (
    3, 'Technika Dnes', 2025, 'TechPress',
    22, 7, 'čtvrtletník', 'magazín',
    100009, '33334444'
);

-- Vložení doby neodebírání
INSERT INTO Doba_Neodoberania (
    cislo_uctu, zakaznik_id, poradi, zacatek, konec
) VALUES (
    100002, 1, 1,
    TO_DATE('2025-07-01', 'YYYY-MM-DD'),
    TO_DATE('2025-07-31', 'YYYY-MM-DD')
);

INSERT INTO Doba_Neodoberania (
    cislo_uctu, zakaznik_id, poradi, zacatek, konec
) VALUES (
    100005, 3, 1,
    TO_DATE('2025-08-01', 'YYYY-MM-DD'),
    TO_DATE('2025-08-15', 'YYYY-MM-DD')
);



-- Vložení vztahu zakaznik–tiskovina
INSERT INTO Zakaznik_Tiskovina (
    zakaznik_ID, kod_tiskoviny,
    doba_ID_zakaznika, doba_cislo_uctu, doba_poradie,
    platba, zakaznik_cislo_uctu
) VALUES (
    1, 1,
    1, 100002, 1,
    1, 100002
);

-- Zákazník 100004 – tiskovina 2
INSERT INTO Zakaznik_Tiskovina (
    zakaznik_ID, kod_tiskoviny,
    doba_ID_zakaznika, doba_cislo_uctu, doba_poradie,
    platba, zakaznik_cislo_uctu
) VALUES (
    2, 2,
    NULL, NULL, NULL,
    2, 100004
);

-- Zákazník 100005 – tiskovina 3
INSERT INTO Zakaznik_Tiskovina (
    zakaznik_ID, kod_tiskoviny,
    doba_ID_zakaznika, doba_cislo_uctu, doba_poradie,
    platba, zakaznik_cislo_uctu
) VALUES (
    3, 3,
    NULL, NULL, NULL,
    3, 100005
);

-- Zákazník 100006 – tiskovina 2
INSERT INTO Zakaznik_Tiskovina (
    zakaznik_ID, kod_tiskoviny,
    doba_ID_zakaznika, doba_cislo_uctu, doba_poradie,
    platba, zakaznik_cislo_uctu
) VALUES (
    4, 2,
    NULL, NULL, NULL,
    4, 100006
);

-- Zákazník 100007 – tiskovina 3
INSERT INTO Zakaznik_Tiskovina (
    zakaznik_ID, kod_tiskoviny,
    doba_ID_zakaznika, doba_cislo_uctu, doba_poradie,
    platba, zakaznik_cislo_uctu
) VALUES (
    5, 3,
    NULL, NULL, NULL,
    5, 100007
);

INSERT INTO Zakaznik_Tiskovina (
    zakaznik_ID, kod_tiskoviny,
    doba_ID_zakaznika, doba_cislo_uctu, doba_poradie,
    platba, zakaznik_cislo_uctu
) VALUES (
    4,             
    1,              -- kod_tiskoviny (Časopis X, doručuje IČO 12345678)
    NULL, NULL, NULL,
    4,              
    100006          
);


-- Vložení seznamu
-- Seznam 1: doručovatel TiskPost s.r.o. (100003, '12345678')
INSERT INTO Seznam (
    cislo_seznamu, datum, kvantita_typu_tiskovin, cislo_uctu, ico_dorucovatele
) VALUES (
    1, SYSDATE, 1, 100003, '12345678'
);

-- Seznam 2: doručovatel DoručXpress (100008, '11112222')
INSERT INTO Seznam (
    cislo_seznamu, datum, kvantita_typu_tiskovin, cislo_uctu, ico_dorucovatele
) VALUES (
    2, SYSDATE, 1, 100008, '11112222'
);

-- Seznam 3: doručovatel MegaPrint CZ (100009, '33334444')
INSERT INTO Seznam (
    cislo_seznamu, datum, kvantita_typu_tiskovin, cislo_uctu, ico_dorucovatele
) VALUES (
    3, SYSDATE, 1, 100009, '33334444'
);

-- Vložení tiskoviny do seznamu
-- Seznam 1 obsahuje Časopis X (kod_tiskoviny = 1)
INSERT INTO Seznam_Tiskovina (
    cislo_seznamu, kod_tiskoviny, kvantita
) VALUES (
    1, 1, 100
);

-- Seznam 2 obsahuje Magazín Móda (kod_tiskoviny = 2)
INSERT INTO Seznam_Tiskovina (
    cislo_seznamu, kod_tiskoviny, kvantita
) VALUES (
    2, 2, 250
);

-- Seznam 3 obsahuje Technika Dnes (kod_tiskoviny = 3)
INSERT INTO Seznam_Tiskovina (
    cislo_seznamu, kod_tiskoviny, kvantita
) VALUES (
    3, 3, 300
);

-- Dotazy

-- Zobrazí všetchny platby uskutečněné zákazníky
SELECT z.jmeno_prijmeni, p.variabilnysymbol, p.suma, p.datum
FROM Zakaznik z
JOIN Platba p ON z.cislo_uctu = p.cislo_odesilatele;

-- Zjistí, který doručovatel distribuuje jaké tiskoviny
SELECT t.nazev, d.nazev_spolecnosti
FROM Tiskovina t
JOIN Dorucovatel d 
  ON t.dorucovatel_cislo_uctu = d.cislo_uctu 
 AND t.dorucovatel_ico = d.ico;


-- Zjistí, který zákazník zaplatil kterou tiskovinu
SELECT z.jmeno_prijmeni, t.nazev, p.suma, p.datum
FROM Zakaznik z
JOIN Zakaznik_Tiskovina zt 
  ON z.cislo_uctu = zt.zakaznik_cislo_uctu 
 AND z.id = zt.zakaznik_ID
JOIN Tiskovina t 
  ON t.kod_tiskoviny = zt.kod_tiskoviny
JOIN Platba p 
  ON p.ID = zt.platba;

--koľik zákazníků bydlí na jednotlivých adresách
SELECT adresa, COUNT(*) AS pocet_zakazniku
FROM Zakaznik
GROUP BY adresa;

--jaký je celkový prijem každého doručovatele
SELECT d.nazev_spolecnosti, p.cislo_prijimatele, SUM(p.suma) AS celkova_suma
FROM Platba p
JOIN Dorucovatel d ON p.cislo_prijimatele = d.cislo_uctu
GROUP BY d.nazev_spolecnosti, p.cislo_prijimatele;

-- Zobrazí zákazníky, kteří si dočasně prerušili odber
SELECT z.jmeno_prijmeni
FROM Zakaznik z
WHERE EXISTS (
    SELECT 1
    FROM Doba_Neodoberania d
    WHERE d.cislo_uctu = z.cislo_uctu
      AND d.zakaznik_id = z.id
      AND d.konec IS NOT NULL
);

-- Zobrazí jmená zákazníkov, ktorí majú predplatné na tlačoviny doručované firmou s IČO 12345678.
SELECT z.jmeno_prijmeni
FROM Zakaznik z
WHERE z.cislo_uctu IN (
    SELECT zt.zakaznik_cislo_uctu
    FROM Zakaznik_Tiskovina zt
    JOIN Tiskovina t 
      ON zt.kod_tiskoviny = t.kod_tiskoviny
    WHERE t.dorucovatel_ico = '12345678'
);